/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hacienda_lechuza;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfDocument;
import com.itextpdf.text.pdf.PdfGState;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDate;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sebitas
 */
public class Facturacion extends javax.swing.JFrame {
DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form Facturacion
     */
    public Facturacion() {
        initComponents();
        this.setLocationRelativeTo(this);
        String [] title = {"Numero ID","Correo Cliente","Receptor","Servicio","CAByS","Tipo de pago","Monto","IVA","Total"};
        dtm.setColumnIdentifiers(title);
        table.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtmonto = new javax.swing.JTextField();
        txtcedula1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnomservicio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcabys = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtimpuesto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btn_facturar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        txtTipoPago = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 134, 190));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 134, 190));
        jLabel2.setText("Nombre del servicio");

        jLabel3.setBackground(new java.awt.Color(0, 134, 190));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 134, 190));
        jLabel3.setText("Nombre Del Receptor");

        jLabel4.setBackground(new java.awt.Color(0, 134, 190));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 134, 190));
        jLabel4.setText("Numero de identificacion");

        jLabel5.setBackground(new java.awt.Color(0, 134, 190));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 134, 190));
        jLabel5.setText("Datos de informacion");

        txtnombre.setBackground(new java.awt.Color(204, 204, 204));
        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtmonto.setBackground(new java.awt.Color(204, 204, 204));
        txtmonto.setForeground(new java.awt.Color(0, 0, 0));
        txtmonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmontoActionPerformed(evt);
            }
        });

        txtcedula1.setBackground(new java.awt.Color(204, 204, 204));
        txtcedula1.setForeground(new java.awt.Color(0, 0, 0));
        txtcedula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedula1ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 134, 190));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 134, 190));
        jLabel6.setText("Codigo CAByS");

        txtnomservicio.setBackground(new java.awt.Color(204, 204, 204));
        txtnomservicio.setForeground(new java.awt.Color(0, 0, 0));
        txtnomservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomservicioActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 134, 190));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 134, 190));
        jLabel7.setText("Monto a cobrar");

        txtcabys.setBackground(new java.awt.Color(204, 204, 204));
        txtcabys.setForeground(new java.awt.Color(0, 0, 0));
        txtcabys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcabysActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 134, 190));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 134, 190));
        jLabel8.setText("Impuesto");

        txtimpuesto.setBackground(new java.awt.Color(204, 204, 204));
        txtimpuesto.setForeground(new java.awt.Color(0, 0, 0));
        txtimpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimpuestoActionPerformed(evt);
            }
        });

        table.setBackground(new java.awt.Color(204, 204, 204));
        table.setForeground(new java.awt.Color(0, 0, 0));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero ID", "Correo cliente", "Receptor", "Servicio", "CAByS", "Tipo de pago", "Monto", "IVA", "Total"
            }
        ));
        jScrollPane1.setViewportView(table);

        btn_facturar.setBackground(new java.awt.Color(0, 134, 190));
        btn_facturar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btn_facturar.setForeground(new java.awt.Color(255, 255, 255));
        btn_facturar.setText("Facturar");
        btn_facturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facturarActionPerformed(evt);
            }
        });

        btn_actualizar.setBackground(new java.awt.Color(0, 134, 190));
        btn_actualizar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btn_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(0, 134, 190));
        btn_eliminar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        txtTipoPago.setBackground(new java.awt.Color(204, 204, 204));
        txtTipoPago.setForeground(new java.awt.Color(0, 0, 0));
        txtTipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoPagoActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 134, 190));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 134, 190));
        jLabel9.setText("Correo del Cliente");

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 134, 190));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 134, 190));
        jLabel10.setText("Tipo de pago");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(btn_facturar)
                .addGap(274, 274, 274)
                .addComponent(btn_actualizar)
                .addGap(271, 271, 271)
                .addComponent(btn_eliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtcedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnomservicio, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtcabys, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtimpuesto))))))
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomservicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcabys, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtimpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_facturar)
                    .addComponent(btn_actualizar)
                    .addComponent(btn_eliminar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Volver Al Login");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtmontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontoActionPerformed

    private void txtcedula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedula1ActionPerformed

    private void txtnomservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomservicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomservicioActionPerformed

    private void txtcabysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcabysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcabysActionPerformed

    private void txtimpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimpuestoActionPerformed

    private void btn_facturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facturarActionPerformed
        // TODO add your handling code here:
        int monto = Integer.parseInt(txtmonto.getText());
        int iva = Integer.parseInt(txtimpuesto.getText());
        float iva_total = (float) (monto*(iva/100.0));
        float total = monto+((iva/100.0f)*monto);
        
        dtm.addRow(new Object[]{
            txtcedula1.getText(),
            txtEmail.getText(),
            txtnombre.getText(),
            txtnomservicio.getText(),
            txtcabys.getText(),
            txtTipoPago.getText(),
            txtmonto.getText(),
            iva_total,
            total
        });
        
        
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        LocalDate fecha = LocalDate.now();
        String fechaString = fecha.toString();
        String filename = txtnombre.getText() +"_"+ fecha +"_"+ txtcabys.getText() + ".pdf";
        int input = JOptionPane.showConfirmDialog(null, "Desea guardar una factura con esta informacion?");
        if (input == 0) {
            int result = chooser.showOpenDialog(null);

            if (result == JFileChooser.APPROVE_OPTION) {
                File selectedFolder = chooser.getSelectedFile();
                System.out.println("Selected folder: " + selectedFolder.getAbsolutePath());

                File file = new File(selectedFolder.getAbsolutePath() + File.separator + filename);

                try {
                    FileOutputStream fos = new FileOutputStream(file);

                    com.itextpdf.text.Document document = new com.itextpdf.text.Document();

                    PdfWriter writer = PdfWriter.getInstance(document, fos);

                    document.open();
                    
                    String iv = String.valueOf(iva_total);
                    String to = String.valueOf(total);
                    float threecol = 190f;
                    float twocol = 285f;
                    float twocol150 = twocol + 150f;
                    float[] twocolumnwidth = {twocol150, twocol};
                    float[] fullwidth = {threecol * 3};

                    PdfPTable table = new PdfPTable(twocolumnwidth.length); // Number of columns

                    // Create a bold font
                    Font boldFont = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD);

                    // Create the first cell with bold text
                    PdfPCell cell1 = new PdfPCell(new Phrase("Lechuza Soluciones", boldFont));
                    cell1.setBorder(PdfPCell.NO_BORDER);
                    table.addCell(cell1);

                    // Create a nested table
                    PdfPTable nestedTable = new PdfPTable(2); // 2 columns
                    Font nestedBoldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);

                    // Add cells to the nested table
                    nestedTable.addCell(new PdfPCell(new Phrase("Fecha", nestedBoldFont)));
                    nestedTable.addCell(new PdfPCell(new Phrase(fechaString)));
                    nestedTable.addCell(new PdfPCell(new Phrase("CAByS", nestedBoldFont)));
                    nestedTable.addCell(new PdfPCell(new Phrase(txtcabys.getText())));

                    // Add the nested table to the main table
                    PdfPCell nestedCell = new PdfPCell(nestedTable);
                    nestedCell.setBorder(PdfPCell.NO_BORDER);
                    nestedCell.setPadding(10f); // Add padding for spacing
                    table.addCell(nestedCell);

                    // Add the main table to the document
                    document.add(table);
                    document.add(new Paragraph("\n")); // Add a line break for spacing

                    // Create a divider table with a border
                    PdfPTable divider = new PdfPTable(fullwidth.length);
                    divider.setWidthPercentage(100); // Set width percentage to 100
                    for (int i = 0; i < fullwidth.length; i++) {
                        divider.addCell(new PdfPCell()); // Add empty cell for the divider
                    }

 
                    for (PdfPCell dividerCell : divider.getRow(0).getCells()) {
                        dividerCell.setBorderWidth(2);
                        dividerCell.setBorderColor(BaseColor.GRAY);
                        dividerCell.setBackgroundColor(BaseColor.LIGHT_GRAY); 
                    }

 
                    document.add(divider);
                    document.add(new Paragraph("\n")); 

       
                    PdfPTable serviceTable = new PdfPTable(3);
                    serviceTable.setWidthPercentage(100); 

      
                    Font headerFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
                    BaseColor grayColor = BaseColor.LIGHT_GRAY; 
            
                    
                    PdfPCell servicioCell = new PdfPCell(new Phrase("Servicio", headerFont));
                    servicioCell.setBackgroundColor(grayColor); 
                    servicioCell.setBorder(PdfPCell.NO_BORDER);
                    serviceTable.addCell(servicioCell);

                    PdfPCell montoCell = new PdfPCell(new Phrase("Monto", headerFont));
                    montoCell.setBackgroundColor(grayColor);
                    montoCell.setBorder(PdfPCell.NO_BORDER);
                    serviceTable.addCell(montoCell);

                    PdfPCell ivaCell = new PdfPCell(new Phrase("IVA", headerFont));
                    ivaCell.setBackgroundColor(grayColor); 
                    ivaCell.setBorder(PdfPCell.NO_BORDER);
                    serviceTable.addCell(ivaCell);
                    

                    serviceTable.addCell(new PdfPCell(new Phrase(txtnomservicio.getText())));
                    serviceTable.addCell(new PdfPCell(new Phrase(txtmonto.getText())));
                    serviceTable.addCell(new PdfPCell(new Phrase(txtimpuesto.getText()+"%")));


                    PdfPCell emptyCell = new PdfPCell(new Phrase("")); 
                    emptyCell.setBorder(PdfPCell.NO_BORDER); 
                    serviceTable.addCell(emptyCell);
                    

                    PdfPCell totalLabelCell = new PdfPCell(new Phrase("IVA")); 
                    totalLabelCell.setBorder(PdfPCell.NO_BORDER);
                    totalLabelCell.setBackgroundColor(grayColor);
                    serviceTable.addCell(totalLabelCell);
                    
                    PdfPCell totalValueCell = new PdfPCell(new Phrase(iv)); 
                    serviceTable.addCell(totalValueCell);
                    
                    
                    PdfPCell emptyCell2 = new PdfPCell(new Phrase("")); 
                    emptyCell2.setBorder(PdfPCell.NO_BORDER); 
                    serviceTable.addCell(emptyCell2);
                    
                    PdfPCell totalLabelCell1 = new PdfPCell(new Phrase("TOTAL")); 
                    totalLabelCell1.setBorder(PdfPCell.NO_BORDER);
                    totalLabelCell1.setBackgroundColor(grayColor);
                    serviceTable.addCell(totalLabelCell1);
                    
                    PdfPCell totalValueCell1 = new PdfPCell(new Phrase(to)); 
                    serviceTable.addCell(totalValueCell1);
                                   
                    document.add(serviceTable);
                    
                    document.close();
                    fos.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                System.out.println("No folder was selected.");
            }
        }

    }//GEN-LAST:event_btn_facturarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
        int monto = Integer.parseInt(txtmonto.getText());
        int iva = Integer.parseInt(txtimpuesto.getText());
        float iva_total = (float) (monto*(iva/100.0));
        float total = monto+((iva/100.0f)*monto);
        int row = table.getSelectedRow();
        dtm.setValueAt(txtcedula1.getText(), row, 0);
        dtm.setValueAt(txtEmail.getText(), row, 1);
        dtm.setValueAt(txtnombre.getText(), row, 3);
        dtm.setValueAt(txtnomservicio.getText(), row, 4);
        dtm.setValueAt(txtcabys.getText(), row, 5);
        dtm.setValueAt(txtTipoPago.getText(), row, 6);
        dtm.setValueAt(txtmonto.getText(), row, 7);
        dtm.setValueAt(iva_total,row,8);
        dtm.setValueAt(total,row,9);
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        dtm.removeRow(row);
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        loginp l = new loginp();
        l.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void txtTipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoPagoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_facturar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtTipoPago;
    private javax.swing.JTextField txtcabys;
    private javax.swing.JTextField txtcedula1;
    private javax.swing.JTextField txtimpuesto;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnomservicio;
    // End of variables declaration//GEN-END:variables
}
